# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/jupyter-workflow-nbdev',
                'doc_host': 'https://miwojc.github.io',
                'git_url': 'https://github.com/miwojc/jupyter-workflow-nbdev',
                'lib_path': 'jupyter_workflow_nbdev'},
  'syms': {'jupyter_workflow_nbdev.core': {'jupyter_workflow_nbdev.core.foo': ('core.html#foo', 'jupyter_workflow_nbdev/core.py')}}}
