# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/jupyter-workflow-nbdev-test',
                'doc_host': 'https://miwojc.github.io',
                'git_url': 'https://github.com/miwojc/jupyter-workflow-nbdev-test',
                'lib_path': 'jupyter_workflow_nbdev_test'},
  'syms': { 'jupyter_workflow_nbdev_test.jupyter_workflow': { 'jupyter_workflow_nbdev_test.jupyter_workflow.get_fremont_data': ( 'jupyter_workflow.html#get_fremont_data',
                                                                                                                                 'jupyter_workflow_nbdev_test/jupyter_workflow.py'),
                                                              'jupyter_workflow_nbdev_test.jupyter_workflow.say_hello': ( 'jupyter_workflow.html#say_hello',
                                                                                                                          'jupyter_workflow_nbdev_test/jupyter_workflow.py')}}}
