# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/jupyter_workflow.ipynb.

# %% auto 0
__all__ = ['FREMONT_URL', 'get_fremont_data']

# %% ../nbs/jupyter_workflow.ipynb 2
from urllib.request import urlretrieve
from pathlib import Path
import pandas as pd

# %% ../nbs/jupyter_workflow.ipynb 3
FREMONT_URL = "https://data.seattle.gov/api/views/65db-xm6k/rows.csv?accessType=DOWNLOAD"

# %% ../nbs/jupyter_workflow.ipynb 4
def get_fremont_data(url:str=FREMONT_URL,  # Web location of the file
                     filename:str='Fremont.csv', # Location of the file on drive
                     force_download:bool=False # if True the redownload
                    ) -> pd.DataFrame:
    """Function return pandas DataFrame based on the url"""
    if force_download or not Path(filename).exists():
        urlretrieve(url=FREMONT_URL, filename='Fremont.csv')
    data = pd.read_csv(filename, index_col='Date', parse_dates=True)
    data.columns = ['Total', 'East', 'West']
    return data
